name: Build Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn package -B
      
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: MaceLimit
          path: target/MaceLimit-1.0.jar
